export const PokemonTypeMap = {
    bug: {
        background: 'bg-backgroundType-bug',
        type: 'bg-types-bug',
        text: 'text-types-bug',
        border: 'border-types-bug',
    },
    dark: {
        background: 'bg-backgroundType-dark',
        type: 'bg-types-dark',
        text: 'text-types-dark',
        border: 'border-types-dark',
    },
    dragon: {
        background: 'bg-backgroundType-dragon',
        type: 'bg-types-dragon',
        text: 'text-types-dragon',
        border: 'border-types-dragon',
    },
    electric: {
        background: 'bg-backgroundType-electric',
        type: 'bg-types-electric',
        text: 'text-types-electric',
        border: 'border-types-electric',
    },
    fairy: {
        background: 'bg-backgroundType-fairy',
        type: 'bg-types-fairy',
        text: 'text-types-fairy',
        border: 'border-types-fairy',
    },
    fighting: {
        background: 'bg-backgroundType-fighting',
        type: 'bg-types-fighting',
        text: 'text-types-fighting',
        border: 'border-types-fighting',
    },
    fire: {
        background: 'bg-backgroundType-fire',
        type: 'bg-types-fire',
        text: 'text-types-fire',
        border: 'border-types-fire',
    },
    flying: {
        background: 'bg-backgroundType-flying',
        type: 'bg-types-flying',
        text: 'text-types-flying',
        border: 'border-types-flying',
    },
    ghost: {
        background: 'bg-backgroundType-ghost',
        type: 'bg-types-ghost',
        text: 'text-types-ghost',
        border: 'border-types-ghost',
    },
    grass: {
        background: 'bg-backgroundType-grass',
        type: 'bg-types-grass',
        text: 'text-types-grass',
        border: 'border-types-grass',
    },
    ground: {
        background: 'bg-backgroundType-ground',
        type: 'bg-types-ground',
        text: 'text-types-ground',
        border: 'border-types-ground',
    },
    ice: {
        background: 'bg-backgroundType-ice',
        type: 'bg-types-ice',
        text: 'text-types-ice',
        border: 'border-types-ice',
    },
    normal: {
        background: 'bg-backgroundType-normal',
        type: 'bg-types-normal',
        text: 'text-types-normal',
        border: 'border-types-normal',
    },
    poison: {
        background: 'bg-backgroundType-poison',
        type: 'bg-types-poison',
        text: 'text-types-poison',
        border: 'border-types-poison',
    },
    psychic: {
        background: 'bg-backgroundType-psychic',
        type: 'bg-types-psychic',
        text: 'text-types-psychic',
        border: 'border-types-psychic',
    },
    rock: {
        background: 'bg-backgroundType-rock',
        type: 'bg-types-rock',
        text: 'text-types-rock',
        border: 'border-types-rock',
    },
    steel: {
        background: 'bg-backgroundType-steel',
        type: 'bg-types-steel',
        text: 'text-types-steel',
        border: 'border-types-steel',
    },
    water: {
        background: 'bg-backgroundType-water',
        type: 'bg-types-water',
        text: 'text-types-water',
        border: 'border-types-water',
    },
}